packages:
  - apps/*
  - packages/*
  - tooling/*
  - infra/cloudflare/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - es5-ext
  - esbuild
  - gifsicle
  - jpegtran-bin
  - ngrok
  - optipng-bin
  - sharp
  - workerd
